### ISSUE TITLE
Default matrix storage mode

### ISSUE THREAD

**Issue by victorapm** [ROCm/rocSPARSE#304]
Hi all, this is not an issue so I'm not following the template. I'm wondering if it makes more sense to set the default storage mode of a `_rocsparse_mat_descr` to unsorted here:

https://github.com/ROCmSoftwarePlatform/rocSPARSE/blob/d8e35fc37ea738c599a6ca7f97ad2fddd275a622/library/src/include/handle.h#L110

I'm bringing this up because recently we hit a bug in hypre during sparse matrix/matrix multiplication that was quite time-consuming to debug. It turned out that the current rocSPARSE implementation for SpGEMM requires the columns of a given row to be sorted and we didn't have that. Had the default storage mode of a rocsparse matrix be "unsorted", we would have figured out the bug much quicker. Having said that, we could always have called `rocsparse_set_mat_storage_method` with `rocsparse_storage_mode_unsorted` for our matrices...

**Comment by ntrost57** [comment]
Hi @victorapm
While I understand the issue you were observing, we do not want to modify the current default behavior, as it has high potential to break existing code (some routines would simply fail to run when sorted mode is not explicitly set, in that case). We will discuss if we can find a suitable solution and get back to you.

**Comment by ntrost57** [comment]
Depending on your sparsity pattern, SpGEMM already works on many unsorted matrices. Currently, we have no plans on extending this. Is this not the case for your matrix?

**Comment by doctorcolinsmith** [comment]
Closing as there is no additional follow up from the reporter.

**Comment by victorapm** [comment]
Oops, I missed your message, Nico! Sorry about that. I guess this has been solved in one of our previous conversations.
