### ISSUE TITLE
rocsparse_spsv not implemented for triangular matrices

### ISSUE THREAD

**Issue by jakub-homola** [ROCm/rocSPARSE#314]
### What is the expected behavior
[The docs](https://rocsparse.readthedocs.io/en/rocm-5.5.1/usermanual.html#rocsparse-spsv) state, that "rocsparse_spsv_solve solves a sparse triangular linear system ...". Calling the `rocsparse_spsv` with a triangular sparse matrix (that is, a `rocsparse_spmat_descr` where I set the attribute `rocsparse_spmat_matrix_type` to `rocsparse_matrix_type_triangular`) should work without issues and not return an error.

### What actually happens
The function exits with error 2, corresponding to `rocsparse_status_not_implemented`.

### How to reproduce
Probably not needed, will provide simple example if necessary

### Environment
all

The most probable cause is e.g. [this line of code](https://github.com/ROCmSoftwarePlatform/rocSPARSE/blob/55faab8be177d4eb0d83b57d4abfaf4222860177/library/src/level2/rocsparse_csrsv_buffer_size.cpp#LL75C16-L75C16), which makes the function accept only general matrices, triangular matrices fail with the error. This is present in other functions too.

Hipyfying (or roc-ifying) from cuSPARSE, where the matrix_type and storage_mode attributes do not exist at all, it might make sense to also accept general matrices. But it is weird that *only* general matrices are accepted. When working just with rocsparse, this behaviour is very unexpected. Why does the matrix_type attribute even exist, when using it breaks the code?

**Comment by jsandham** [comment]
Support for `rocsparse_matrix_type_triangular` in `rocsparse_spsv` merged to develop. This addition will be part of an upcoming release.
